server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: inst-score-service
  datasource:
    url: jdbc:postgresql://postgres-score:5432/score
    username: postgres
    password: 1234
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate